// Tries to load the full dataset generated by build_unihan_data.py.
// Falls back to the small bundled sample if jianzi_data.json isn't
// present yet, or if the page was opened directly via file:// (browsers
// block fetch() of local files that way — see README for how to serve
// the page properly with serve.py).
function briefDef(e) {
  const full = e.chinese_definition || e.definition || "";
  if (!full) return "(no definition on file)";
  // show up to the first newline or sentence-end, max 60 chars
  const cut = full.split(/\n|[。！？；;!?]/)[0].trim();
  return cut.length > 60 ? cut.slice(0, 60) + "…" : cut || "(no definition on file)";
}

async function loadJianziEntries() {
  try {
    const res = await fetch("jianzi_data.json", { cache: "no-store" });
    if (!res.ok) throw new Error("jianzi_data.json not found (status " + res.status + ")");
    const raw = await res.json();
    if (!Array.isArray(raw) || raw.length === 0) throw new Error("jianzi_data.json is empty");

    return {
      entries: raw.map(e => ({
        w: e.word,
        r: e.radical,
        rs: e.residual_strokes,
        ts: e.total_strokes,
        py: e.pinyin || "",
        def: briefDef(e),
        fullDef: e.chinese_definition || "",
      })),
      source: "full",
    };
  } catch (err) {
    // When opened directly as file://, fetch() is blocked by the browser.
    // Use the browser-safe full dataset instead of silently dropping to the tiny sample.
    if (Array.isArray(window.JIANZI_FULL_DATA) && window.JIANZI_FULL_DATA.length) {
      return {
        entries: window.JIANZI_FULL_DATA.map(e => ({
          w: e.word,
          r: e.radical,
          rs: e.residual_strokes,
          ts: e.total_strokes,
          py: e.pinyin || "",
          def: briefDef(e),
          fullDef: e.chinese_definition || "",
        })),
        source: "full-inline",
      };
    }
    console.warn("[jianzi] Falling back to sample data:", err.message);
    return { entries: SAMPLE_ENTRIES, source: "sample" };
  }
}
