// Tries to load the full dataset generated by build_unihan_data.py.
// Falls back to the small bundled sample if jianzi_data.json isn't
// present yet, or if the page was opened directly via file:// (browsers
// block fetch() of local files that way — see README for how to serve
// the page properly with serve.py).
async function loadJianziEntries() {
  try {
    const res = await fetch("jianzi_data.json", { cache: "no-store" });
    if (!res.ok) throw new Error("jianzi_data.json not found (status " + res.status + ")");
    const raw = await res.json();
    if (!Array.isArray(raw) || raw.length === 0) throw new Error("jianzi_data.json is empty");

    return {
      entries: raw.map(e => ({
        w: e.word,
        r: e.radical,
        rs: e.residual_strokes,
        ts: e.total_strokes,
        py: e.pinyin || "",
        def: e.definition || "(no definition on file)",
      })),
      source: "full",
    };
  } catch (err) {
    console.warn("[jianzi] Falling back to sample data:", err.message);
    return { entries: window.SAMPLE_ENTRIES, source: "sample" };
  }
}
