// The complete, standard 214 Kangxi radical table (as codified in the
// 1716 Kangxi Dictionary and used by virtually every Chinese dictionary
// since — including Xinhua Zidian). This is universal reference data,
// not sourced from any specific dictionary project.
//
// Fields:
//   no       Kangxi radical number, 1-214
//   char     the radical's standalone glyph
//   variant  alternate/positional form(s) as they appear inside characters, if any
//   strokes  stroke count of the radical itself
//   pinyin   Mandarin reading
//   meaning  short English gloss
const KANGXI_RADICALS_FULL = [
  // 1 stroke
  {no:1,char:"一",strokes:1,pinyin:"yī",meaning:"one"},
  {no:2,char:"丨",strokes:1,pinyin:"gǔn",meaning:"line"},
  {no:3,char:"丶",strokes:1,pinyin:"zhǔ",meaning:"dot"},
  {no:4,char:"丿",strokes:1,pinyin:"piě",meaning:"slash"},
  {no:5,char:"乙",strokes:1,pinyin:"yǐ",meaning:"second; twisting"},
  {no:6,char:"亅",strokes:1,pinyin:"jué",meaning:"hook"},

  // 2 strokes
  {no:7,char:"二",strokes:2,pinyin:"èr",meaning:"two"},
  {no:8,char:"亠",strokes:2,pinyin:"tóu",meaning:"lid"},
  {no:9,char:"人",variant:"亻",strokes:2,pinyin:"rén",meaning:"person"},
  {no:10,char:"儿",strokes:2,pinyin:"ér",meaning:"legs"},
  {no:11,char:"入",strokes:2,pinyin:"rù",meaning:"enter"},
  {no:12,char:"八",strokes:2,pinyin:"bā",meaning:"eight"},
  {no:13,char:"冂",strokes:2,pinyin:"jiōng",meaning:"down box"},
  {no:14,char:"冖",strokes:2,pinyin:"mì",meaning:"cover"},
  {no:15,char:"冫",strokes:2,pinyin:"bīng",meaning:"ice"},
  {no:16,char:"几",strokes:2,pinyin:"jī",meaning:"table"},
  {no:17,char:"凵",strokes:2,pinyin:"kǎn",meaning:"open box"},
  {no:18,char:"刀",variant:"刂",strokes:2,pinyin:"dāo",meaning:"knife"},
  {no:19,char:"力",strokes:2,pinyin:"lì",meaning:"power"},
  {no:20,char:"勹",strokes:2,pinyin:"bāo",meaning:"wrap"},
  {no:21,char:"匕",strokes:2,pinyin:"bǐ",meaning:"spoon"},
  {no:22,char:"匚",strokes:2,pinyin:"fāng",meaning:"box"},
  {no:23,char:"匸",strokes:2,pinyin:"xì",meaning:"hiding enclosure"},
  {no:24,char:"十",strokes:2,pinyin:"shí",meaning:"ten"},
  {no:25,char:"卜",strokes:2,pinyin:"bǔ",meaning:"divination"},
  {no:26,char:"卩",variant:"㔾",strokes:2,pinyin:"jié",meaning:"seal"},
  {no:27,char:"厂",strokes:2,pinyin:"hàn",meaning:"cliff"},
  {no:28,char:"厶",strokes:2,pinyin:"sī",meaning:"private"},
  {no:29,char:"又",strokes:2,pinyin:"yòu",meaning:"again; right hand"},
  {no:30,char:"口",strokes:3,pinyin:"kǒu",meaning:"mouth"},
  {no:31,char:"囗",strokes:3,pinyin:"wéi",meaning:"enclosure"},
  {no:32,char:"土",strokes:3,pinyin:"tǔ",meaning:"earth"},
  {no:33,char:"士",strokes:3,pinyin:"shì",meaning:"scholar"},

  // 3 strokes
  {no:34,char:"夂",strokes:3,pinyin:"zhǐ",meaning:"go"},
  {no:35,char:"夊",strokes:3,pinyin:"suī",meaning:"go slowly"},
  {no:36,char:"夕",strokes:3,pinyin:"xī",meaning:"evening"},
  {no:37,char:"大",strokes:3,pinyin:"dà",meaning:"big"},
  {no:38,char:"女",strokes:3,pinyin:"nǚ",meaning:"woman"},
  {no:39,char:"子",strokes:3,pinyin:"zǐ",meaning:"child"},
  {no:40,char:"宀",strokes:3,pinyin:"mián",meaning:"roof"},
  {no:41,char:"寸",strokes:3,pinyin:"cùn",meaning:"inch"},
  {no:42,char:"小",variant:"⺌",strokes:3,pinyin:"xiǎo",meaning:"small"},
  {no:43,char:"尢",variant:"尣",strokes:3,pinyin:"wāng",meaning:"lame"},
  {no:44,char:"尸",strokes:3,pinyin:"shī",meaning:"corpse"},
  {no:45,char:"屮",strokes:3,pinyin:"chè",meaning:"sprout"},
  {no:46,char:"山",strokes:3,pinyin:"shān",meaning:"mountain"},
  {no:47,char:"巛",variant:"川",strokes:3,pinyin:"chuān",meaning:"river"},
  {no:48,char:"工",strokes:3,pinyin:"gōng",meaning:"work"},
  {no:49,char:"己",strokes:3,pinyin:"jǐ",meaning:"self"},
  {no:50,char:"巾",strokes:3,pinyin:"jīn",meaning:"cloth"},
  {no:51,char:"干",strokes:3,pinyin:"gān",meaning:"dry; shield"},
  {no:52,char:"幺",strokes:3,pinyin:"yāo",meaning:"short thread"},
  {no:53,char:"广",strokes:3,pinyin:"guǎng",meaning:"shelter"},
  {no:54,char:"廴",strokes:3,pinyin:"yǐn",meaning:"long stride"},
  {no:55,char:"廾",strokes:3,pinyin:"gǒng",meaning:"two hands"},
  {no:56,char:"弋",strokes:3,pinyin:"yì",meaning:"shoot; dart"},
  {no:57,char:"弓",strokes:3,pinyin:"gōng",meaning:"bow"},
  {no:58,char:"彐",variant:"彑",strokes:3,pinyin:"jì",meaning:"snout"},
  {no:59,char:"彡",strokes:3,pinyin:"shān",meaning:"bristle"},
  {no:60,char:"彳",strokes:3,pinyin:"chì",meaning:"step"},

  // 4 strokes
  {no:61,char:"心",variant:"忄",strokes:4,pinyin:"xīn",meaning:"heart"},
  {no:62,char:"戈",strokes:4,pinyin:"gē",meaning:"halberd"},
  {no:63,char:"户",variant:"戸",strokes:4,pinyin:"hù",meaning:"door"},
  {no:64,char:"手",variant:"扌",strokes:4,pinyin:"shǒu",meaning:"hand"},
  {no:65,char:"支",strokes:4,pinyin:"zhī",meaning:"branch"},
  {no:66,char:"攴",variant:"攵",strokes:4,pinyin:"pū",meaning:"rap, tap"},
  {no:67,char:"文",strokes:4,pinyin:"wén",meaning:"script"},
  {no:68,char:"斗",strokes:4,pinyin:"dǒu",meaning:"dipper"},
  {no:69,char:"斤",strokes:4,pinyin:"jīn",meaning:"axe"},
  {no:70,char:"方",strokes:4,pinyin:"fāng",meaning:"square"},
  {no:71,char:"无",variant:"旡",strokes:4,pinyin:"wú",meaning:"not"},
  {no:72,char:"日",strokes:4,pinyin:"rì",meaning:"sun"},
  {no:73,char:"曰",strokes:4,pinyin:"yuē",meaning:"say"},
  {no:74,char:"月",strokes:4,pinyin:"yuè",meaning:"moon"},
  {no:75,char:"木",strokes:4,pinyin:"mù",meaning:"tree"},
  {no:76,char:"欠",strokes:4,pinyin:"qiàn",meaning:"lack; owe"},
  {no:77,char:"止",strokes:4,pinyin:"zhǐ",meaning:"stop"},
  {no:78,char:"歹",variant:"歺",strokes:4,pinyin:"dǎi",meaning:"death"},
  {no:79,char:"殳",strokes:4,pinyin:"shū",meaning:"weapon"},
  {no:80,char:"毋",strokes:4,pinyin:"wú",meaning:"do not"},
  {no:81,char:"比",strokes:4,pinyin:"bǐ",meaning:"compare"},
  {no:82,char:"毛",strokes:4,pinyin:"máo",meaning:"fur"},
  {no:83,char:"氏",strokes:4,pinyin:"shì",meaning:"clan"},
  {no:84,char:"气",strokes:4,pinyin:"qì",meaning:"steam"},
  {no:85,char:"水",variant:"氵",strokes:4,pinyin:"shuǐ",meaning:"water"},
  {no:86,char:"火",variant:"灬",strokes:4,pinyin:"huǒ",meaning:"fire"},
  {no:87,char:"爪",variant:"爫",strokes:4,pinyin:"zhǎo",meaning:"claw"},
  {no:88,char:"父",strokes:4,pinyin:"fù",meaning:"father"},
  {no:89,char:"爻",strokes:4,pinyin:"yáo",meaning:"trigrams"},
  {no:90,char:"爿",variant:"丬",strokes:4,pinyin:"qiáng",meaning:"half tree trunk"},
  {no:91,char:"片",strokes:4,pinyin:"piàn",meaning:"slice"},
  {no:92,char:"牙",strokes:4,pinyin:"yá",meaning:"fang"},
  {no:93,char:"牛",variant:"牜",strokes:4,pinyin:"niú",meaning:"cow"},
  {no:94,char:"犬",variant:"犭",strokes:4,pinyin:"quǎn",meaning:"dog"},

  // 5 strokes
  {no:95,char:"玄",strokes:5,pinyin:"xuán",meaning:"profound"},
  {no:96,char:"玉",variant:"王",strokes:5,pinyin:"yù",meaning:"jade"},
  {no:97,char:"瓜",strokes:5,pinyin:"guā",meaning:"melon"},
  {no:98,char:"瓦",strokes:5,pinyin:"wǎ",meaning:"tile"},
  {no:99,char:"甘",strokes:5,pinyin:"gān",meaning:"sweet"},
  {no:100,char:"生",strokes:5,pinyin:"shēng",meaning:"life"},
  {no:101,char:"用",strokes:5,pinyin:"yòng",meaning:"use"},
  {no:102,char:"田",strokes:5,pinyin:"tián",meaning:"field"},
  {no:103,char:"疋",variant:"⺪",strokes:5,pinyin:"pǐ",meaning:"bolt of cloth"},
  {no:104,char:"疒",strokes:5,pinyin:"nè",meaning:"sickness"},
  {no:105,char:"癶",strokes:5,pinyin:"bō",meaning:"footsteps"},
  {no:106,char:"白",strokes:5,pinyin:"bái",meaning:"white"},
  {no:107,char:"皮",strokes:5,pinyin:"pí",meaning:"skin"},
  {no:108,char:"皿",strokes:5,pinyin:"mǐn",meaning:"dish"},
  {no:109,char:"目",strokes:5,pinyin:"mù",meaning:"eye"},
  {no:110,char:"矛",strokes:5,pinyin:"máo",meaning:"spear"},
  {no:111,char:"矢",strokes:5,pinyin:"shǐ",meaning:"arrow"},
  {no:112,char:"石",strokes:5,pinyin:"shí",meaning:"stone"},
  {no:113,char:"示",variant:"礻",strokes:5,pinyin:"shì",meaning:"spirit"},
  {no:114,char:"禸",strokes:5,pinyin:"róu",meaning:"track"},
  {no:115,char:"禾",strokes:5,pinyin:"hé",meaning:"grain"},
  {no:116,char:"穴",strokes:5,pinyin:"xué",meaning:"cave"},
  {no:117,char:"立",strokes:5,pinyin:"lì",meaning:"stand"},

  // 6 strokes
  {no:118,char:"竹",variant:"⺮",strokes:6,pinyin:"zhú",meaning:"bamboo"},
  {no:119,char:"米",strokes:6,pinyin:"mǐ",meaning:"rice"},
  {no:120,char:"糸",variant:"糹",strokes:6,pinyin:"mì",meaning:"silk"},
  {no:121,char:"缶",strokes:6,pinyin:"fǒu",meaning:"jar"},
  {no:122,char:"网",variant:"罒",strokes:6,pinyin:"wǎng",meaning:"net"},
  {no:123,char:"羊",variant:"⺶",strokes:6,pinyin:"yáng",meaning:"sheep"},
  {no:124,char:"羽",strokes:6,pinyin:"yǔ",meaning:"feather"},
  {no:125,char:"老",variant:"耂",strokes:6,pinyin:"lǎo",meaning:"old"},
  {no:126,char:"而",strokes:6,pinyin:"ér",meaning:"and; beard"},
  {no:127,char:"耒",strokes:6,pinyin:"lěi",meaning:"plow"},
  {no:128,char:"耳",strokes:6,pinyin:"ěr",meaning:"ear"},
  {no:129,char:"聿",strokes:6,pinyin:"yù",meaning:"brush"},
  {no:130,char:"肉",variant:"月",strokes:6,pinyin:"ròu",meaning:"meat"},
  {no:131,char:"臣",strokes:6,pinyin:"chén",meaning:"minister"},
  {no:132,char:"自",strokes:6,pinyin:"zì",meaning:"self"},
  {no:133,char:"至",strokes:6,pinyin:"zhì",meaning:"arrive"},
  {no:134,char:"臼",strokes:6,pinyin:"jiù",meaning:"mortar"},
  {no:135,char:"舌",strokes:6,pinyin:"shé",meaning:"tongue"},
  {no:136,char:"舛",strokes:6,pinyin:"chuǎn",meaning:"oppose"},
  {no:137,char:"舟",strokes:6,pinyin:"zhōu",meaning:"boat"},
  {no:138,char:"艮",strokes:6,pinyin:"gèn",meaning:"stopping"},
  {no:139,char:"色",strokes:6,pinyin:"sè",meaning:"color"},
  {no:140,char:"艸",variant:"艹",strokes:6,pinyin:"cǎo",meaning:"grass"},
  {no:141,char:"虍",strokes:6,pinyin:"hū",meaning:"tiger"},
  {no:142,char:"虫",strokes:6,pinyin:"chóng",meaning:"insect"},
  {no:143,char:"血",strokes:6,pinyin:"xuè",meaning:"blood"},
  {no:144,char:"行",strokes:6,pinyin:"xíng",meaning:"walk enclosure"},
  {no:145,char:"衣",variant:"衤",strokes:6,pinyin:"yī",meaning:"clothes"},
  {no:146,char:"襾",variant:"西",strokes:6,pinyin:"yà",meaning:"cover; west"},

  // 7 strokes
  {no:147,char:"見",strokes:7,pinyin:"jiàn",meaning:"see"},
  {no:148,char:"角",strokes:7,pinyin:"jiǎo",meaning:"horn"},
  {no:149,char:"言",variant:"訁",strokes:7,pinyin:"yán",meaning:"speech"},
  {no:150,char:"谷",strokes:7,pinyin:"gǔ",meaning:"valley"},
  {no:151,char:"豆",strokes:7,pinyin:"dòu",meaning:"bean"},
  {no:152,char:"豕",strokes:7,pinyin:"shǐ",meaning:"pig"},
  {no:153,char:"豸",strokes:7,pinyin:"zhì",meaning:"badger"},
  {no:154,char:"貝",strokes:7,pinyin:"bèi",meaning:"shell; money"},
  {no:155,char:"赤",strokes:7,pinyin:"chì",meaning:"red"},
  {no:156,char:"走",strokes:7,pinyin:"zǒu",meaning:"run"},
  {no:157,char:"足",variant:"⻊",strokes:7,pinyin:"zú",meaning:"foot"},
  {no:158,char:"身",strokes:7,pinyin:"shēn",meaning:"body"},
  {no:159,char:"車",strokes:7,pinyin:"chē",meaning:"cart"},
  {no:160,char:"辛",strokes:7,pinyin:"xīn",meaning:"bitter"},
  {no:161,char:"辰",strokes:7,pinyin:"chén",meaning:"morning"},
  {no:162,char:"辵",variant:"辶",strokes:7,pinyin:"chuò",meaning:"walk"},
  {no:163,char:"邑",variant:"阝",strokes:7,pinyin:"yì",meaning:"city"},
  {no:164,char:"酉",strokes:7,pinyin:"yǒu",meaning:"wine"},
  {no:165,char:"釆",strokes:7,pinyin:"biàn",meaning:"distinguish"},
  {no:166,char:"里",strokes:7,pinyin:"lǐ",meaning:"village"},

  // 8 strokes
  {no:167,char:"金",variant:"釒",strokes:8,pinyin:"jīn",meaning:"gold; metal"},
  {no:168,char:"長",variant:"镸",strokes:8,pinyin:"cháng",meaning:"long"},
  {no:169,char:"門",strokes:8,pinyin:"mén",meaning:"gate"},
  {no:170,char:"阜",variant:"阝",strokes:8,pinyin:"fù",meaning:"mound"},
  {no:171,char:"隶",strokes:8,pinyin:"lì",meaning:"slave; reach"},
  {no:172,char:"隹",strokes:8,pinyin:"zhuī",meaning:"short-tailed bird"},
  {no:173,char:"雨",strokes:8,pinyin:"yǔ",meaning:"rain"},
  {no:174,char:"青",strokes:8,pinyin:"qīng",meaning:"blue; green"},
  {no:175,char:"非",strokes:8,pinyin:"fēi",meaning:"wrong"},

  // 9 strokes
  {no:176,char:"面",strokes:9,pinyin:"miàn",meaning:"face"},
  {no:177,char:"革",strokes:9,pinyin:"gé",meaning:"leather"},
  {no:178,char:"韋",strokes:9,pinyin:"wéi",meaning:"tanned leather"},
  {no:179,char:"韭",strokes:9,pinyin:"jiǔ",meaning:"leek"},
  {no:180,char:"音",strokes:9,pinyin:"yīn",meaning:"sound"},
  {no:181,char:"頁",strokes:9,pinyin:"yè",meaning:"leaf; page; head"},
  {no:182,char:"風",strokes:9,pinyin:"fēng",meaning:"wind"},
  {no:183,char:"飛",strokes:9,pinyin:"fēi",meaning:"fly"},
  {no:184,char:"食",variant:"飠",strokes:9,pinyin:"shí",meaning:"eat"},
  {no:185,char:"首",strokes:9,pinyin:"shǒu",meaning:"head"},
  {no:186,char:"香",strokes:9,pinyin:"xiāng",meaning:"fragrant"},

  // 10 strokes
  {no:187,char:"馬",strokes:10,pinyin:"mǎ",meaning:"horse"},
  {no:188,char:"骨",strokes:10,pinyin:"gǔ",meaning:"bone"},
  {no:189,char:"高",strokes:10,pinyin:"gāo",meaning:"tall"},
  {no:190,char:"髟",strokes:10,pinyin:"biāo",meaning:"hair"},
  {no:191,char:"鬥",strokes:10,pinyin:"dòu",meaning:"fight"},
  {no:192,char:"鬯",strokes:10,pinyin:"chàng",meaning:"sacrificial wine"},
  {no:193,char:"鬲",strokes:10,pinyin:"lì",meaning:"cauldron"},
  {no:194,char:"鬼",strokes:10,pinyin:"guǐ",meaning:"ghost"},

  // 11 strokes
  {no:195,char:"魚",strokes:11,pinyin:"yú",meaning:"fish"},
  {no:196,char:"鳥",strokes:11,pinyin:"niǎo",meaning:"bird"},
  {no:197,char:"鹵",strokes:11,pinyin:"lǔ",meaning:"salt"},
  {no:198,char:"鹿",strokes:11,pinyin:"lù",meaning:"deer"},
  {no:199,char:"麥",strokes:11,pinyin:"mài",meaning:"wheat"},
  {no:200,char:"麻",strokes:11,pinyin:"má",meaning:"hemp"},

  // 12 strokes
  {no:201,char:"黃",strokes:12,pinyin:"huáng",meaning:"yellow"},
  {no:202,char:"黍",strokes:12,pinyin:"shǔ",meaning:"millet"},
  {no:203,char:"黑",strokes:12,pinyin:"hēi",meaning:"black"},
  {no:204,char:"黹",strokes:12,pinyin:"zhǐ",meaning:"embroidery"},

  // 13 strokes
  {no:205,char:"黽",strokes:13,pinyin:"mǐn",meaning:"frog"},
  {no:206,char:"鼎",strokes:13,pinyin:"dǐng",meaning:"tripod"},
  {no:207,char:"鼓",strokes:13,pinyin:"gǔ",meaning:"drum"},
  {no:208,char:"鼠",strokes:13,pinyin:"shǔ",meaning:"rat"},

  // 14 strokes
  {no:209,char:"鼻",strokes:14,pinyin:"bí",meaning:"nose"},
  {no:210,char:"齊",strokes:14,pinyin:"qí",meaning:"even"},

  // 15 strokes
  {no:211,char:"齒",strokes:15,pinyin:"chǐ",meaning:"tooth"},

  // 16 strokes
  {no:212,char:"龍",strokes:16,pinyin:"lóng",meaning:"dragon"},
  {no:213,char:"龜",strokes:16,pinyin:"guī",meaning:"turtle"},

  // 17 strokes
  {no:214,char:"龠",strokes:17,pinyin:"yuè",meaning:"flute"},
];

if (typeof module !== "undefined") module.exports = { KANGXI_RADICALS_FULL };
